### ISSUE TITLE
Setup Error in HA Core 2024.1.6

### ISSUE THREAD

**Issue by garyak** [nalin29/control4RoomMedia#4]
Custom component will not initialize in recently released HA Core 2024.1.6, HA log error:
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

```
2024-02-01 07:55:02.851 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry control4_ea5_000FFF1B47F9 for control4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 75, in async_setup_entry
    director_token_dict = await account.getDirectorBearerToken(controller_unique_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/account.py", line 234, in getDirectorBearerToken
    data = await self.__sendControllerAuthRequest(controller_common_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyControl4/account.py", line 137, in __sendControllerAuthRequest
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by garyak** [comment]
HAOS 11.5 seems to have corrected the issue.

**Comment by garyak** [comment]
Error has returned for HA 2024.2.1
```
2024-02-11 12:25:01.571 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry control4_ea5_000FFF1B47F9 for control4
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/control4/__init__.py", line 75, in async_setup_entry
    director_token_dict = await account.getDirectorBearerToken(controller_unique_id)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyControl4/account.py", line 234, in getDirectorBearerToken
    data = await self.__sendControllerAuthRequest(controller_common_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyControl4/account.py", line 137, in __sendControllerAuthRequest
    async with self.session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by garyak** [comment]
I guess it's my installation having issues.
